<?php

namespace Paypal\Bundle\PaypalBundle\Repository;

/**
 * PaypalOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaypalOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
